FROM ubuntu:18.04
MAINTAINER Chenhao Li

RUN apt-get update --fix-missing

ENV VERSION=2.0.8-beta
RUN apt-get install -y python3-pip
RUN pip3 install humann2
RUN apt-get install -y bowtie2

ADD humann2_main.py /usr/local/lib/python3.6/dist-packages/humann2/humann2.py
ADD humann2_search_nucleotide.py /usr/local/lib/python3.6/dist-packages/humann2/search/nucleotide.py